-- Create the database
CREATE DATABASE RealEstateAgencyDB;

-- Switch to the new database
USE RealEstateAgencyDB;

-- Supprimer la table si elle existe
IF OBJECT_ID('dbo.Agents', 'U') IS NOT NULL
    DROP TABLE dbo.Agents;
-- AGENTS TABLE
CREATE TABLE Agents (
    AgentID INT PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Phone NVARCHAR(50),
    Email NVARCHAR(100) UNIQUE
);


IF OBJECT_ID('dbo.Customers', 'U') IS NOT NULL
    DROP TABLE dbo.Customers;

-- CUSTOMERS TABLE
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Phone NVARCHAR(50),
    Email NVARCHAR(100)
    
);

-- Supprimer la table si elle existe
IF OBJECT_ID('dbo.Properties', 'U') IS NOT NULL
    DROP TABLE dbo.Properties;

-- PROPERTIES TABLE
CREATE TABLE Properties (
    PropertyID INT PRIMARY KEY,
    PropertyType NVARCHAR(50), -- Apartment, House, Office, etc.
    Location NVARCHAR(50),
    Size_sqm DECIMAL(10,2),
    PriceUSD DECIMAL(15,2)
 
);

-- SALES TABLE
CREATE TABLE Sales (
    SaleID INT PRIMARY KEY,
    PropertyID INT NOT NULL,
    CustomerID INT NOT NULL,
    AgentID INT NOT NULL,
    SaleDate DATE,
    SalePrice DECIMAL(15,2),
    CONSTRAINT FK_Sales_Properties FOREIGN KEY (PropertyID)
        REFERENCES Properties(PropertyID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT FK_Sales_Customers FOREIGN KEY (CustomerID)
        REFERENCES Customers(CustomerID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT FK_Sales_Agents FOREIGN KEY (AgentID)
        REFERENCES Agents(AgentID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

-- VISITS TABLE
CREATE TABLE Visits (
    VisitID INT PRIMARY KEY,
    CustomerID INT NOT NULL,
    PropertyID INT NOT NULL,
    AgentID INT NOT NULL,
    VisitDate DATE,
    CONSTRAINT FK_Visits_Properties FOREIGN KEY (PropertyID)
        REFERENCES Properties(PropertyID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT FK_Visits_Customers FOREIGN KEY (CustomerID)
        REFERENCES Customers(CustomerID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT FK_Visits_Agents FOREIGN KEY (AgentID)
        REFERENCES Agents(AgentID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

--Providing Data To Our Tables Using Our Csv files.
INSERT INTO Agents (AgentID,FirstName, LastName, Phone, Email)
SELECT AgentID,FirstName, LastName, Phone, Email FROM Agents_temp;

INSERT INTO Customers (CustomerID,FirstName,LastName,Phone,Email)
SELECT CustomerID,FirstName,LastName,Phone,Email FROM Customers_temp;

INSERT INTO Properties (PropertyID,PropertyType, Location, Size_sqm, PriceUSD) 
SELECT PropertyID,PropertyType, Location, Size_sqm, PriceUSD FROM Properties_temp;

INSERT INTO Sales (SaleID,PropertyID, CustomerID,AgentID, SaleDate, SalePrice) 
SELECT SaleID,PropertyID, CustomerID,AgentID, SaleDate, SalePrice FROM Sales_temp;

INSERT INTO Visits (VisitID,PropertyID, CustomerID, AgentID, VisitDate) 
SELECT VisitID,PropertyID, CustomerID, AgentID, VisitDate FROM Visits_temp;

--We drop unnecessary tables
DROP TABLE IF EXISTS Agents_temp, Customers_temp, Properties_temp, Sales_temp, Visits_temp;

--Executing Queries
SELECT * FROM Sales;

--Answers To Questions About The situation of Real Estate Activity

--Q1 : Total number of Properties
SELECT COUNT(*) AS total_properties
FROM Properties;

--Q2 : Total number of Properties by Type
SELECT PropertyType, COUNT(*) AS total_properties
FROM Properties
GROUP BY PropertyType
ORDER BY total_properties DESC;

--Q3 : Average price by PropertyType
SELECT PropertyType, ROUND(AVG(PriceUSD), 2) AS Avg_price
FROM Properties
GROUP BY PropertyType
ORDER BY Avg_price DESC;

--Q4 : Top 10 Most Expensive Properties
SELECT TOP 10 PropertyID, PropertyType, PriceUSD, Size_sqm
FROM Properties
ORDER BY PriceUSD DESC;

--Q5 : Average price by Location and PropertyType
SELECT Location, PropertyType, ROUND(AVG(PriceUSD), 2) AS Avg_price
FROM Properties
GROUP BY Location, PropertyType
ORDER BY avg_price DESC;

--Q6 : Number of Sales made by each Agent
SELECT a.AgentID, a.FirstName, a.LastName, COUNT(s.SaleID) AS Sales_count
FROM Sales s
JOIN Agents a ON s.AgentID = a.AgentID
GROUP BY a.AgentID, a.FirstName, a.LastName
ORDER BY sales_count DESC;

--Q7 : Turnover per agent to provide the sales and profit generated by each agent
SELECT 
    a.AgentID, 
    a.FirstName, 
    a.LastName,
    ROUND(SUM(s.SalePrice), 2) AS Total_sales,
    ROUND(SUM(CASE 
                WHEN s.SalePrice >= p.PriceUSD 
                THEN s.SalePrice - p.PriceUSD 
                ELSE 0 
              END), 2) AS Total_profit
FROM Sales s
JOIN Agents a ON s.AgentID = a.AgentID
JOIN Properties p ON s.PropertyID = p.PropertyID
GROUP BY a.AgentID, a.FirstName, a.LastName
ORDER BY Total_sales DESC;

--Q8 : Agent performance (sales/visit conversion rate)
SELECT 
    a.AgentID, 
    a.FirstName, 
    a.LastName,
    COUNT(DISTINCT v.VisitID) AS Total_visits,
    COUNT(DISTINCT s.SaleID) AS Total_sales,
    ROUND(COUNT(DISTINCT s.SaleID) * 100.0 / COUNT(DISTINCT v.VisitID), 2) AS Conversion_rate
FROM Agents a
LEFT JOIN Visits v ON a.AgentID = v.AgentID
LEFT JOIN Sales s ON a.AgentID = s.AgentID
GROUP BY a.AgentID, a.FirstName, a.LastName
HAVING COUNT(DISTINCT v.VisitID) > 0
ORDER BY Conversion_rate DESC;

--Q9 : Sales evolution by month
SELECT YEAR(SaleDate) AS Year, MONTH(SaleDate) AS Month, 
       COUNT(SaleID) AS Sales_Count, 
       ROUND(SUM(SalePrice), 2) AS Total_Sales
FROM Sales
GROUP BY YEAR(SaleDate), MONTH(SaleDate)
ORDER BY Year, Month;

--Q10 : Average time between VisitDate and SaleDate
SELECT 
    p.PropertyType, 
    ROUND(AVG(DATEDIFF(DAY, v.VisitDate, s.SaleDate)), 2) AS avg_days_on_market
FROM Properties p
JOIN Sales s ON p.PropertyID = s.PropertyID
JOIN Visits v ON p.PropertyID = v.PropertyID
WHERE v.VisitDate <= s.SaleDate
GROUP BY p.PropertyType;

--Q11 : Top 5 most requested locations
SELECT TOP 5 p.Location, COUNT(v.VisitID) AS total_visits
FROM Visits v
JOIN Properties p ON v.PropertyID = p.PropertyID
GROUP BY p.Location
ORDER BY total_visits DESC;

--Q12 : Customers who have purchased multiple properties
SELECT c.CustomerID, c.FirstName, c.LastName, 
       COUNT(s.SaleID) AS Purchase_Count,
       ROUND(SUM(s.SalePrice), 2) AS Total_Spent
FROM Customers c
JOIN sales s ON c.CustomerID = s.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
HAVING COUNT(s.SaleID) > 1
ORDER BY Purchase_Count DESC;

--Q13 : Price per m² by Location
SELECT 
    p.Location, 
    ROUND(AVG(p.PriceUSD / p.Size_sqm), 2) AS Price_Per_Sqft
FROM Properties p
WHERE p.Size_sqm > 0
GROUP BY p.Location
ORDER BY Price_Per_Sqft DESC;

--Q14 : Properties never visited
SELECT p.PropertyID, p.PropertyType, p.PriceUSD, p.Location
FROM Properties p
LEFT JOIN Visits v ON p.PropertyID = v.PropertyID
WHERE v.VisitID IS NULL;

--Q15 : Correlation between price and area
SELECT 
    ROUND(
        (COUNT(*) * SUM(PriceUSD * Size_sqm) - SUM(PriceUSD) * SUM(Size_sqm)) /
        (SQRT(COUNT(*) * SUM(PriceUSD * PriceUSD) - SUM(PriceUSD) * SUM(PriceUSD)) * 
         SQRT(COUNT(*) * SUM(Size_sqm * Size_sqm) - SUM(Size_sqm) * SUM(Size_sqm))),
    2) AS correlation_coefficient
FROM Properties
WHERE Size_sqm > 0 AND PriceUSD > 0;

--Q16 : Average price of properties sold vs. not sold
SELECT 
    CASE WHEN s.SaleID IS NOT NULL THEN 'Vendu' ELSE 'Non vendu' END AS Status,
    COUNT(p.PropertyID) AS Property_Count,
    ROUND(AVG(p.PriceUSD), 2) AS Avg_price
FROM Properties p
LEFT JOIN Sales s ON p.PropertyID = s.PropertyID
GROUP BY CASE WHEN s.SaleID IS NOT NULL THEN 'Vendu' ELSE 'Non vendu' END;

--Q17 : Top 5 months with the most sales
SELECT TOP 5 YEAR(SaleDate) AS Year, MONTH(SaleDate) AS Month, 
       COUNT(SaleID) AS Sales_Count
FROM Sales
GROUP BY YEAR(SaleDate), MONTH(SaleDate)
ORDER BY Sales_Count DESC;

--Q18 : Agents with the most visits
SELECT a.AgentID, a.FirstName, a.LastName, 
       COUNT(v.VisitID) AS Visit_Count
FROM Agents a
JOIN Visits v ON a.AgentID = v.AgentID
GROUP BY a.AgentID, a.FirstName, a.LastName
ORDER BY Visit_Count DESC;

--Q19 : Customers with the most visits without purchase
SELECT c.CustomerID, c.FirstName, c.LastName,
       COUNT(v.VisitID) AS Visit_Count
FROM Customers c
JOIN Visits v ON c.CustomerID = v.CustomerID
LEFT JOIN Sales s ON c.CustomerID = s.CustomerID AND v.PropertyID = s.PropertyID
WHERE s.SaleID IS NULL
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY Visit_Count DESC;

--Q20 : Percentage of properties sold within 30 days
SELECT 
    ROUND(
        SUM(CASE 
                WHEN DATEDIFF(DAY, v.VisitDate, s.SaleDate) <= 30 THEN 1 
                ELSE 0 
            END) * 100.0 / COUNT(*), 2
    ) AS sold_within_30_days
FROM Sales s
JOIN Properties p ON s.PropertyID = p.PropertyID
JOIN Visits v ON s.PropertyID = v.PropertyID
WHERE v.VisitDate <= s.SaleDate;

--Q21 : Customers who also became sellers
SELECT DISTINCT c.CustomerID, c.FirstName, c.LastName
FROM Customers c
JOIN Sales s1 ON c.CustomerID = s1.CustomerID
JOIN Properties p ON s1.PropertyID = p.PropertyID
JOIN Sales s2 ON p.PropertyID = s2.PropertyID
WHERE s2.CustomerID != c.CustomerID;
